### ISSUE TITLE
Roadmap for new features

### ISSUE THREAD

**Issue by AnthonyKuang** [project-lumiere/lumiere.codes#61]
- [ ] Markdown linting
- [ ] Real-time collaborative editing
- [ ] Custom theming output
- [ ] Custom domains - free transfer to your own domain!
